CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(512)    NOT NULL,
    name                VARCHAR(255)    NOT NULL,
    CONSTRAINT uq_user_email    UNIQUE (email),
    CONSTRAINT uq_user_name     UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS categories (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(64)     NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude            REAL            NOT NULL,
    longitude           REAL            NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          VARCHAR(2000)   NOT NULL,
    category_id         BIGINT          NOT NULL    REFERENCES categories (id) ON DELETE CASCADE,
    confirmed_requests  INTEGER         NOT NULL    DEFAULT 0,
    created_date        TIMESTAMP       NOT NULL,
    description         TEXT            NOT NULL,
    event_date          TIMESTAMP       NOT NULL,
    initiator_id        BIGINT          NOT NULL    REFERENCES users (id)      ON DELETE CASCADE,
    location_id         BIGINT                      REFERENCES locations (id)  ON DELETE SET NULL,
    paid                BOOLEAN         NOT NULL    DEFAULT 0,
    participant_limit   INTEGER         NOT NULL    DEFAULT 0,
    published_date      TIMESTAMP,
    request_moderation  BOOLEAN         NOT NULL    DEFAULT 1,
    state               VARCHAR(24)     NOT NULL,
    title               VARCHAR(120)    NOT NULL,
    views               BIGINT          NOT NULL    DEFAULT 0
);

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN         NOT NULL    DEFAULT 0,
    title               VARCHAR(128)    NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id      BIGINT          NOT NULL    REFERENCES compilations (id)    ON DELETE CASCADE,
    event_id            BIGINT          NOT NULL    REFERENCES events (id)          ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created             TIMESTAMP       NOT NULL,
    event_id            BIGINT          NOT NULL    REFERENCES events (id) ON DELETE CASCADE,
    requester_id        BIGINT          NOT NULL    REFERENCES users (id)  ON DELETE CASCADE,
    status              VARCHAR(24)     NOT NULL,
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
);