
CREATE TABLE IF NOT EXISTS views (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    ip              VARCHAR(39)     NOT NULL,
    request_date    TIMESTAMP       NOT NULL,
    uri             VARCHAR(512)    NOT NULL
);